---

- name: "pull haproxy image"
  docker_image:
    name: "{{ HAProxy_Image_Name }}"
    source: pull

- name: "run haproxy container as a service"
  template:
    src: templates/haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
  notify:
   - "reload-daemon to apply changes"
   - "enable haproxy service"
   - "start haproxy service"