---
- name: "Download Docker compose"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0644

- name: "Create symbolic link for docker-compose"
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    owner: ubuntu
    group: ubuntu
    state: link