---
# handlers file for pull_containers

- name: "reload-daemon to apply changes"
  command: sudo systemctl daemon-reload

- name: "start haproxy service"
  service:
    name: haproxy
    state: restarted

- name: "enable haproxy service"
  service:
    name: haproxy
    enabled: yes

