- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - ca-certificates 
    - curl
    - gnupg
    - apt-transport-https
    - software-properties-common


- name: "Install docker-py"
  pip:
    name: docker-py

- name: "Add gpg key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present


- name: "Add docker repository"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    update_cache: true

    state: present


- name: "update and install docker"
  apt:
    name: "{{ item }}"
    update_cache: yes
  
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io


- name: "docker login"
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"